### ISSUE TITLE
"No records found in file" returned for valid FASTQ

### ISSUE THREAD

**Issue by sminot** [onecodex/onecodex-uploader#12]
Selecting the file 

`@SRR2148846.9280 HISEQ:184:C2L3GACXX:6:1101:21026:11255 length=202
AAGAGGCTGCTGTTTCATTCGGATCAGGGAGGGCAGTACAGGAGTAAGAAATCCAGGCAGTTACTGTGGAGGACCGGAGTGATGCAGAGTATGAGCCGCANGTTGTAATAACTTTGTATCCATTCACCGNNATCTCGTACCGCATGATGGACATCCATATAGCCCCCTACAGGCAGCCATTCACTTTTCAGGCTTCGGAACN
+SRR2148846.9280 HISEQ:184:C2L3GACXX:6:1101:21026:11255 length=202
@@CFFFFFHHHHHJJIJJJJJJIJIGJIIEIIIHIIGIIIFIDGCFGGGIJIJFHC@GHHHHGHFFEFFFDD=ABBBDD?BCEDDDDDDC>CDDDCC@BDDBBBFDDBBFHHHHIIIGIIJJJJGIHHI##2<CFHCFDEGHIIIGICHGIF@GGGIJIJGFHIDH<EEHEC@?C?C6?CCFECDDDCDC@@C<?C/.8<@B`

with the filename `search_service restart.fastq` results in the error "No Records Found in File"

**Comment by boydgreenfield** [comment]
cc @bovee – any idea what's going on here?
