### ISSUE TITLE
[feature] Interleave paired end reads

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex-uploader#4]

**Comment by bovee** [comment]
Needs two things:
 - [ ] a reliable way to detect read pairs (find/replace R1 with R2 and see how many matchs? will fail for e.g. R100.fq, R101.fq ... R199.fq, R200.fq)
 - [ ] some graphical way for users to break up reads that get incorrectly paired

**Comment by bovee** [comment]
This is now supported in the CLI/client library and we should rebase/use that for uploads during the next refactor cycle of this.

**Comment by clausmith** [comment]
Will potentially be solved by onecodex/fastx-proxy
